// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egbpjvbrqtvxtlpqkszr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnYnBqdmJycXR2eHRscHFrc3pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzM5NzQsImV4cCI6MjA1OTM0OTk3NH0.90u6Thhc8fDRT5uLcDK2-suSynoe_HW6j8aUAmf7YLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);